[pytest]
testpaths = tests
pythonpath = .
markers =
    integration: tests that require external services (not used in ci workflows)
    unit: tests that does not require external services (used in ci workflows)